#!/bin/bash
#SBATCH --job-name=INF
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24           # 16 CPUs are generally sufficient for DataLoader on GPU nodes
#SBATCH --mem=110000                 
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:1                 # Request 1 GPU (adjust format based on Viper docs, e.g., gpu:A100:1 if needed)
#SBATCH --output=slurm_inf-%j.out
#SBATCH --mail-type=END,FAIL         
#SBATCH --mail-user=wenting.wang.cd@outlook.com

# Recommended AI environment variables by MPCDF (prevents node crashes from excessive threading)
export OMP_WAIT_POLICY=PASSIVE
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# Scratch Directory Setup for fast I/O
SCRATCH_DIRECTORY=/ptmp/${USER}/${SLURM_JOBID}
mkdir -p "${SCRATCH_DIRECTORY}"
echo "Running in scratch directory: ${SCRATCH_DIRECTORY}"

cd "${SCRATCH_DIRECTORY}"

# ==========================================
# 1. Copy required files to the scratch directory
# ==========================================
cp "${SLURM_SUBMIT_DIR}/train_e2e_v14_gpu.py" .
cp "${SLURM_SUBMIT_DIR}/orders.csv" .
cp "${SLURM_SUBMIT_DIR}/pomdp_posterior.csv" .
cp -r "${SLURM_SUBMIT_DIR}/core/"    .

# Copy all dataset parts generated by the CPU array tasks
# cp "${SLURM_SUBMIT_DIR}"/*.pt .
cp "${SLURM_SUBMIT_DIR}"/e2e_dataset_5000_additive_1_finetune_part_*.pt .
# cp "${SLURM_SUBMIT_DIR}"/e2e_dataset_5000_additive_2_finetune_part_*.pt .
# cp "${SLURM_SUBMIT_DIR}"/e2e_dataset_5000_multiplicative_finetune_part_*.pt .

# INFERENCE ONLY
# cp "${SLURM_SUBMIT_DIR}/amortized_inference_net_additive_2_finetune.pth" .

# ==========================================
# 2. Load the environment and run the script
# ==========================================
module purge
module load python-waterboa/2025.06

# Activate your custom virtual environment
source ~/rocm_env/bin/activate  

echo ">>> Starting E2E Model GPU Training and Real Data Inference..."
srun python3 -u train_e2e_v14_gpu.py

# ==========================================
# 3. Copy results back to the original directory
# ==========================================
echo ">>> Training & Inference finished. Copying results back to the submit directory..."

# Copy model weights back
# cp *.pth "${SLURM_SUBMIT_DIR}/" 

# Copy parameter recovery plots back
# cp *.png "${SLURM_SUBMIT_DIR}/"

# Copy parameter recovery numerical results and real data inference CSVs back
# cp *.csv "${SLURM_SUBMIT_DIR}/"

echo ">>> Copy complete."
echo ">>> Scratch cleanup bypassed. You can inspect the files at: ${SCRATCH_DIRECTORY}"