name: sst-pomdp-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - joblib
  - pytorch
  - pip
  - statsmodels
  - plotly
  - pip:
    - sbi      # Simulation-Based Inference package
    - tqdm